FROM python:3.13

LABEL CyberDreamer "TheCoporation.space"

RUN useradd thecorporation

WORKDIR /home/thecorporation/flask

RUN pip3 install --upgrade pip

RUN pip3 install versiontools

COPY ./requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

RUN chown -R thecorporation:thecorporation ./

USER thecorporation
