"""empty message

Revision ID: 09814faea7f3
Revises: 
Create Date: 2025-06-09 21:14:37.068102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09814faea7f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('funding', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('inf_account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('inf_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('bets')
        batch_op.drop_column('starting_price')
        batch_op.drop_column('item')
        batch_op.drop_column('prize_claimed')

    with op.batch_alter_table('inf_auction_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'inf_auction', ['auction_id'], ['id'])

    with op.batch_alter_table('inf_rank', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('inf_tribute', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('influence', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('jwt_blacklist', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('jwt_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('influence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('inf_tribute', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('inf_rank', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('inf_auction_bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('auction_id')

    with op.batch_alter_table('inf_auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_claimed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('starting_price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('inf_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('funding', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
