# Use an official Nginx image as the base image
FROM nginx:alpine

# Remove default Nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy static website files to the Nginx document root
COPY ./web/ /usr/share/nginx/html